### ISSUE TITLE
Problem with fileio

### ISSUE THREAD

**Issue by hemkumarsrinivas** [HarrisonKramer/optiland#27]
Hi,
I tried running the example script, where you explain how we can load a zemax file from the Thorlabs catalogue. The module fileio does not seem to be installed with the current version, when installed with pip. Only manually copying the files and saving them to a fileio subdirectory inside the optiland directory solves this problem. Can this be checked and fixed with the next version ?

**Comment by HarrisonKramer** [comment]
Hi,

Thanks for catching and reporting this. I just fixed this now and republished the latest version on PyPI. The tutorials were run with the latest dev version of Optiland and the PyPI version lags this somewhat.

Thanks!

Kramer
