### ISSUE TITLE
when image plane is tilt, FFT PSF get wrong result

### ISSUE THREAD

**Issue by xuxuxu0701** [HarrisonKramer/optiland#6]
actually, there are two questions i meet:
1. when the image plane tilt with a large degree, as i set [rx=np.radians(45.0)] for the last surface of CookeTriplet, psf can not be calculate
2. when the image plane tilt with a small degree and i try to calculate the psf of small field (large field also error), the rusult are not the same as the result in Zemax, both fft psf and huygens psf

**Comment by HarrisonKramer** [comment]
Thank you for reporting this issue.

### Question 1

- In order to be able to reproduce this issue, can you elaborate on what you mean when you say the PSF "cannot be calculated"? I am able to run the PSF calculation on my machine when the image plane is rotated by 45 degrees, but the computation time does increase substantially (≈30x for me). If possible, a minimum working example reproducing the issue would help here.
- Also note that, in general, the FFT-based PSF algorithm assumes that the chief ray is nearly normal to the image plane. If the image plane is rotated significantly (e.g. 45 degrees), then the FFT PSF will not be accurate.
- I have considered adding something like the "Huygens PSF", which does not make the same assumptions as the FFT PSF and would be accurate even in the case that the image plane is (significantly) tilted. If that's something that would be interesting for you, I can investigate this further.

### Question 2

- I quickly ran the FFT PSF calculation for the Cooke triplet at 0.55 µm with the image plane tilted about the x-axis by 1 degree. I compared this to the equivalent calculation in Zemax. The results appear to be identical, other than variations in the pixel size & image grid size. Can you confirm that you ran the _exact_ same calculation in both Optiland and Zemax? Is it possible you ran the FFT PSF calculation in Zemax using wavelength set to "All" (the default option)?
- I expect the Huygens PSF result to be different, as well as more accurate. As mentioned above, I am happy to investigate adding this feature, if interesting.

Here is the code I used to compute the FFT PSF for the Cooke triplet with an image plane tilt of 1 degree about x:

```python
import numpy as np
from optiland import optic, psf

class CookeTriplet(optic.Optic):
    def __init__(self):
        super().__init__()

        self.add_surface(index=0, radius=np.inf, thickness=np.inf)
        self.add_surface(index=1, radius=22.01359, thickness=3.25896, material='SK16')
        self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
        self.add_surface(index=3, radius=-22.21328, thickness=0.99997, material=('F2', 'schott'))
        self.add_surface(index=4, radius=20.29192, thickness=4.75041, is_stop=True)
        self.add_surface(index=5, radius=79.68360, thickness=2.95208, material='SK16')
        self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
        self.add_surface(index=7, rx=np.radians(1.0))

        self.set_aperture(aperture_type='EPD', value=10)

        self.set_field_type(field_type='angle')
        self.add_field(y=0)
        self.add_field(y=14)
        self.add_field(y=20)

        self.add_wavelength(value=0.48)
        self.add_wavelength(value=0.55, is_primary=True)
        self.add_wavelength(value=0.65)

lens = CookeTriplet()

lens_psf = psf.FFTPSF(lens, field=(0, 1.0), wavelength=0.55)
lens_psf.view(num_points=128)
```

**Comment by xuxuxu0701** [comment]
> Thank you for reporting this issue.
> 
> ### Question 1
> * In order to be able to reproduce this issue, can you elaborate on what you mean when you say the PSF "cannot be calculated"? I am able to run the PSF calculation on my machine when the image plane is rotated by 45 degrees, but the computation time does increase substantially (≈30x for me). If possible, a minimum working example reproducing the issue would help here.
> * Also note that, in general, the FFT-based PSF algorithm assumes that the chief ray is nearly normal to the image plane. If the image plane is rotated significantly (e.g. 45 degrees), then the FFT PSF will not be accurate.
> * I have considered adding something like the "Huygens PSF", which does not make the same assumptions as the FFT PSF and would be accurate even in the case that the image plane is (significantly) tilted. If that's something that would be interesting for you, I can investigate this further.
> 
> ### Question 2
> * I quickly ran the FFT PSF calculation for the Cooke triplet at 0.55 µm with the image plane tilted about the x-axis by 1 degree. I compared this to the equivalent calculation in Zemax. The results appear to be identical, other than variations in the pixel size & image grid size. Can you confirm that you ran the _exact_ same calculation in both Optiland and Zemax? Is it possible you ran the FFT PSF calculation in Zemax using wavelength set to "All" (the default option)?
> * I expect the Huygens PSF result to be different, as well as more accurate. As mentioned above, I am happy to investigate adding this feature, if interesting.
> 
> Here is the code I used to compute the FFT PSF for the Cooke triplet with an image plane tilt of 1 degree about x:
> 
> ```python
> import numpy as np
> from optiland import optic, psf
> 
> class CookeTriplet(optic.Optic):
>     def __init__(self):
>         super().__init__()
> 
>         self.add_surface(index=0, radius=np.inf, thickness=np.inf)
>         self.add_surface(index=1, radius=22.01359, thickness=3.25896, material='SK16')
>         self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
>         self.add_surface(index=3, radius=-22.21328, thickness=0.99997, material=('F2', 'schott'))
>         self.add_surface(index=4, radius=20.29192, thickness=4.75041, is_stop=True)
>         self.add_surface(index=5, radius=79.68360, thickness=2.95208, material='SK16')
>         self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
>         self.add_surface(index=7, rx=np.radians(1.0))
> 
>         self.set_aperture(aperture_type='EPD', value=10)
> 
>         self.set_field_type(field_type='angle')
>         self.add_field(y=0)
>         self.add_field(y=14)
>         self.add_field(y=20)
> 
>         self.add_wavelength(value=0.48)
>         self.add_wavelength(value=0.55, is_primary=True)
>         self.add_wavelength(value=0.65)
> 
> lens = CookeTriplet()
> 
> lens_psf = psf.FFTPSF(lens, field=(0, 1.0), wavelength=0.55)
> lens_psf.view(num_points=128)
> ```

**Comment by xuxuxu0701** [comment]
I use the code below and got error:

```
import numpy as np
from optiland import optic, psf

class CookeTriplet(optic.Optic):
    def __init__(self):
        super().__init__()

        self.add_surface(index=0, radius=np.inf, thickness=np.inf)
        self.add_surface(index=1, radius=22.01359, thickness=3.25896, material='SK16')
        self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
        self.add_surface(index=3, radius=-22.21328, thickness=0.99997, material=('F2', 'schott'))
        self.add_surface(index=4, radius=20.29192, thickness=4.75041, is_stop=True)
        self.add_surface(index=5, radius=79.68360, thickness=2.95208, material='SK16')
        self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
        self.add_surface(index=7, rx=np.radians(45.0))

        self.set_aperture(aperture_type='EPD', value=10)

        self.set_field_type(field_type='angle')
        self.add_field(y=0)
        self.add_field(y=14)
        self.add_field(y=20)

        self.add_wavelength(value=0.48)
        self.add_wavelength(value=0.55, is_primary=True)
        self.add_wavelength(value=0.65)

lens = CookeTriplet()

lens_psf = psf.FFTPSF(lens, field=(0, 0.1), wavelength=0.55)
lens_psf.view(num_points=128)
```
and got error:
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\optiland-master\temp.py", line 31, in <module>
    lens_psf.view(num_points=128)
  File "C:\Users\Administrator\Downloads\optiland-master\optiland\psf.py", line 73, in view
    min_x, min_y, max_x, max_y = self._find_bounds(threshold)
  File "C:\Users\Administrator\Downloads\optiland-master\optiland\psf.py", line 284, in _find_bounds
    min_x, min_y = np.min(non_zero_indices, axis=0)
  File "<__array_function__ internals>", line 200, in amin
  File "D:\software\Anaconda\envs\py39\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "D:\software\Anaconda\envs\py39\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

And when i only change the code like 

`lens_psf = psf.FFTPSF(lens, field=(0, 1), wavelength=0.55)`

the program running normally, just very slow, and got like this 
<img width="525" alt="psfcodelargefov" src="https://github.com/user-attachments/assets/82c5f5c1-b4f3-4acc-b6a1-6b893bdb169c">


For the Q2, I used code below
```
  import numpy as np
  from optiland import optic, psf
  
  
  class CookeTriplet(optic.Optic):
      def __init__(self):
          super().__init__()
  
          self.add_surface(index=0, radius=np.inf, thickness=np.inf)
          self.add_surface(index=1, radius=22.01359, thickness=3.25896,
                           material='SK16')
          self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
          self.add_surface(index=3, radius=-22.21328, thickness=0.99997,
                           material=('F2', 'schott'))
          self.add_surface(index=4, radius=20.29192, thickness=4.75041,
                           is_stop=True)
          self.add_surface(index=5, radius=79.68360, thickness=2.95208,
                           material='SK16')
          self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
          self.add_surface(index=7, rx=np.radians(45.0))
  
          self.set_aperture(aperture_type='EPD', value=10)
  
          self.set_field_type(field_type='angle')
          self.add_field(y=0)
          self.add_field(y=3)
          self.add_field(y=6)
  
          self.add_wavelength(value=0.48)
          self.add_wavelength(value=0.55, is_primary=True)
          self.add_wavelength(value=0.65)
  
          self.update_paraxial()
  lens = CookeTriplet()
  lens_psf = psf.FFTPSF(lens, field=(0, 0.5), wavelength=0.55)
  lens_psf.view(projection='2d', num_points=1024)
```
and got a result like this
<img width="525" alt="psfcode" src="https://github.com/user-attachments/assets/6b37193f-1e64-420f-9dc5-983a0070b458">

compared with the result of fft psf in zemax, it seems different 
<img width="923" alt="zemaxfftpsf" src="https://github.com/user-attachments/assets/a9aa5e85-dc7c-4eac-90bf-d6fc32facdb0">

and the lens data is here
<img width="918" alt="zemaxlesdata" src="https://github.com/user-attachments/assets/227454db-fc5d-4d94-8a10-e57599213d44">

Optiland is the best open-source ray tracing, optical design, and analysis software I have used. It is extremely simple and efficient. I would greatly appreciate it if the Huygens PSF functionality could be added.
